name: "Build Docker Image - Github"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker Image Tag'
        required: true
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Actions Code Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx Context
        id: buildx-context
        run: |
          docker context create builders
      - name: Set up Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
          endpoint: builders
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ACTIONS_DOCKER_USERNAME }}
          password: ${{ secrets.ACTIONS_DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          platforms: linux/arm64,linux/amd64
          push: true
          tags: <Image Name>:${{ github.event.inputs.tag }}
